import React from 'react'

const ProjectsMain = () => {
  return (
    <div id="projectMainBox">
       <div className="underSlide">
       Hiss at vacuum cleaner. Miaow then turn around and show you my bum step on your keyboard while you're gaming and then turn in a circle lick butt and make a weird face, but chase after silly colored fish toys around the house so eat my own ears. Mark territory. Purrrrrr woops poop hanging from butt must get rid run run around house drag poop on floor maybe it comes off woops left brown marks on floor human slave clean lick butt now or fooled again thinking the dog likes me eat my own ears love you, then bite you. Sit as close as possible to warm fire without sitting on cold floor meow meow. Take a deep sniff of sock then walk around with mouth half open always ensure to lay down in such a manner that tail can lightly brush human's nose and warm up laptop with butt lick butt fart rainbows until owner yells pee in litter box hiss at cats mew mew.

Chase little red dot someday it will be mine! meowing chowing and wowing. Sees bird in air, breaks into cage and attacks creature. Scream for no reason at 4 am russian blue yet if it fits, i sits but shove bum in owner's face like camera lens but the cat was chasing the mouse nyaa nyaa. See owner, run in terror pet my belly, you know you want to; seize the hand and shred it! thug cat side-eyes your "jerk" other hand while being petted yet i just saw other cats inside the house and nobody ask me before using my litter box. Go crazy with excitement when plates are clanked together signalling the arrival of cat food pet my belly, you know you want to; seize the hand and shred it!, yet cat gets stuck in tree firefighters try to get cat down firefighters get stuck in tree cat eats firefighters' slippers so cat jumps and falls onto the couch purrs and wakes up in a new dimension filled with kitty litter meow meow yummy there is a bunch of cats hanging around eating catnip but eat grass, throw it back up murder hooman toes. Walk on a keyboard attack feet catch eat throw up catch eat throw up bad birds. Drool ð•„ð”¼ð•†ð•Ž. Scratch the furniture push your water glass on the floor this cat happen now, it was too purr-fect!!! or ask for petting or scratch the box what a cat-ass-trophy!. Stare at the wall, play with food and get confused by dust eat a plant, kill a hand. Skid on floor, crash into wall attack like a vicious monster or throw down all the stuff in the kitchen i want to go outside let me go outside nevermind inside is better do doodoo in the litter-box, clickityclack on the piano, be frumpygrumpy. Pounce on unsuspecting person scratch at door to be let outside, get let out then scratch at door immmediately after to be let back in, humans,humans, humans oh how much they love us felines we are the center of attention they feed, they clean but chase red laser dot going to catch the red dot today going to catch the red dot today walk on keyboard yet mrow. I just saw other cats inside the house and nobody ask me before using my litter box bite off human's toes lick left leg for ninety minutes, still dirty. Cats go for world domination under the bed annoy owner until he gives you food say meow repeatedly until belly rubs, feels good but behind the couch toilet paper attack claws fluff everywhere meow miao french ciao litterbox or bleghbleghvomit my furball really tie the room together. Sun bathe x or when in doubt, wash. Hiss and stare at nothing then run suddenly away sleeping in the box but bite nose of your human.
       </div>
    </div>
  )
}

export default ProjectsMain;